name: CI/CD Spring Boot Angular Docker

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # -------------------------
    # 1️⃣ Checkout codeee
    # -------------------------
    - name: Checkout source code
      uses: actions/checkout@v6

    # -------------------------
    # 2️⃣ BACKEND – Spring Boot
    # --------------------------
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: maven-${{ hashFiles('springboot/app/pom.xml') }}

    - name: Build & Test Spring Boot
      run: |
        cd springboot/app
        chmod +x mvnw
        ./mvnw clean package 
        ./mvnw clean verify

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Backend Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/myapp-backend:$IMAGE_TAG springboot/app
        docker push $DOCKER_USERNAME/myapp-backend:$IMAGE_TAG

    # -------------------------
    # 3️⃣ FRONTEND – Angulare
    # -------------------------

    - name: Build & Push Frontend Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/myapp-frontend:$IMAGE_TAG angular-app
        docker push $DOCKER_USERNAME/myapp-frontend:$IMAGE_TAG

    # -------------------------
    # 4️⃣ test
    # -------------------------
    - name: Run docker compose
      run: |
        docker compose down 
        docker compose up -d
        docker ps
